# Generated by Django 4.0.4 on 2022-05-13 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('answer', models.TextField(null=True)),
                ('file', models.FileField(null=True, upload_to='course/homework/responses')),
                ('sent', models.BooleanField(default=False)),
                ('grade', models.FloatField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Titulo')),
                ('description', models.TextField(null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='courses/homewowrk')),
                ('limit', models.DateField(null=True)),
                ('closed', models.BooleanField(default=False)),
                ('response', models.ManyToManyField(related_name='homework', to='tareas.response')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
    ]
