# Generated by Django 3.2.13 on 2022-05-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Titulo'),
        ),
    ]
