# Generated by Django 3.2.13 on 2022-04-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220418_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('grupo', models.IntegerField()),
                ('titulo', models.CharField(max_length=256)),
                ('contenf', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alumno', models.IntegerField()),
                ('actividad', models.IntegerField()),
                ('calificacion', models.IntegerField()),
            ],
        ),
    ]
