# Generated by Django 4.0.4 on 2022-05-13 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tareas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True, verbose_name='Titulo')),
                ('content', models.TextField(null=True)),
                ('timestamp', models.DateField(auto_now=True)),
                ('homework', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.homework')),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256, null=True)),
                ('activate', models.BooleanField(default=True)),
                ('homework', models.ManyToManyField(related_name='course', to='tareas.homework')),
                ('post', models.ManyToManyField(related_name='course', to='cursos.post')),
                ('professor', models.ManyToManyField(related_name='course_professor', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='student_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
