# Generated by Django 3.2.13 on 2022-05-13 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
