# Generated by Django 4.0.4 on 2022-05-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Num',
            field=models.IntegerField(default=71499),
        ),
    ]
